### ISSUE TITLE
Redesign Roadmap

### ISSUE THREAD

**Issue by abefernan** [cosmos/cosmos-multisig-ui#222]
- [ ] Use shadcn components, react-hook-form, and zod:
  - [ ] Chain selection
  - [ ] Account view
  - [ ] Find multisig form
  - [ ] Multisig info view
  - [ ] Create multisig form
  - [ ] Transaction view
  - [ ] Create Tx form(s)

- [ ] Make all of the above friendly for desktop-sized screens
- [ ] Remove all now unneeded old layout components like `<StackableContainer />`
- [ ] Choose better colors for the shadcn theme using this util: https://ui.jln.dev
